FROM python:3.9-slim

WORKDIR /code

COPY . /code
RUN apt-get update && apt-get install -y libpq-dev gcc && \
pip install --no-cache-dir --upgrade -r /app/requirements.txt && \
apt-get clean && \
rm -rf /var/lib/apt/lists/*

